version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env  # ดึงค่าจาก .env
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for Postgres...';
        while ! nc -z db 5432; do sleep 1; done;
        echo 'Postgres is up!';
        npx prisma migrate dev --name init;
        node server.js
      "

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - app
    command: tunnel --url http://app:3000

# ✅ ส่วนนี้คือการสร้าง volume ชื่อ pgdata
volumes:
  pgdata:
